export const path = {
  home: '/',
  auth: '/auth',
  verifyOtp: 'verify-otp',
  forgotPassword: '/forgot-password',
  courseList: '/course-list',
  courseListByCategory: '/courses/category/:categoryId',
  myLearning: '/my-learning',
  myList: '/my-learning/my-list',
  wishList: '/my-learning/wishlish',
  cart: '/cart',
  payMent: '/payment',
  coursePlayer: '/course-player/:courseId',
  courseDetail: '/course/:id',
  courseForm: '/courses/new',
  userEdit: '/edit-profile',
  userProfile: '/profile',
  users: '/users',
  courses: '/courses',
  dashboard: '/dashboard',
  blog: '/blog',
  contact: '/contact',
  purchaseHistory: '/purchase-history',
  chat: '/messages',
  qnaClient: '/qna/:courseId/:lessonId',
  FlashcardMatchingGame: '/flashcardmatchinggame',
  flashcardGame: '/flashcardgame',
  instructor: {
    instructorDashboard: '/instructor-dashboard',
    QnA: '/QnA',
    addCourse: '/add-course',
    addQuiz: '/add-quiz',
  },
  admin: {
    courseForm: 'admin/courses/new',
    users: 'admin/users',
    courses: 'admin/courses',
    categories: 'admin/categories',
    dashboard: 'admin/dashboard',
    feedback: 'admin/feedback',
    coupon: 'admin/coupon',
    hashtag: 'admin/hashtag',
  },
};
